In [1]:
import pandas as pd
from pathlib import Path

In [2]:
PROJECT_DIR = Path.cwd().parent
PROCESSED_DATA = PROJECT_DIR / "data" / "processed"

print(PROCESSED_DATA)

c:\Users\ashik\OneDrive\Desktop\mutualfundproject\data\processed

In [3]:
sharpe = pd.read_csv(PROCESSED_DATA / "sharpe_ratio.csv")
sortino = pd.read_csv(PROCESSED_DATA / "sortino_ratio.csv")
alpha_beta = pd.read_csv(PROCESSED_DATA / "alpha_beta.csv")
cagr = pd.read_csv(PROCESSED_DATA / "cagr_table.csv")
drawdown = pd.read_csv(PROCESSED_DATA / "max_drawdown.csv")
tracking = pd.read_csv(PROCESSED_DATA / "tracking_error.csv")

In [4]:
sharpe.head()

,amfi_code,mean,std,annual_return,annual_volatility,sharpe_ratio
0,148567,0.001074,0.008941,0.270566,0.141937,1.448291
1,120843,0.001082,0.010008,0.272602,0.158870,1.306744
2,148569,0.001124,0.011134,0.283262,0.176740,1.234930
3,119551,0.000917,0.008656,0.231033,0.137414,1.208267
4,120505,0.001161,0.012152,0.292653,0.192909,1.180101

In [5]:
cagr.head()

   amfi_code  nav_start   nav_end      cagr  cagr_percent
0     120505   135.8720  473.7640  0.328274     32.827406
1     119598    89.8738  309.2050  0.324235     32.423536
2     149324    81.6814  279.7511  0.322874     32.287440
3     148569    28.8620   97.7435  0.319495     31.949523
4     148567    70.2514  230.2708  0.309741     30.974108

In [6]:
alpha_beta.head()

   amfi_code     alpha      beta
0     100016  0.037476 -0.058268
1     100025  0.042818  0.001158
2     100033  0.271954  0.005104
3     101206  0.213998  0.021086
4     101207  0.108971 -0.065289

In [7]:
drawdown.head()

   amfi_code  max_drawdown
0     100016     -0.247344
1     100025     -0.043083
2     100033     -0.162172
3     101206     -0.112916
4     101207     -0.354469

In [8]:
tracking.head()

   amfi_code  tracking_error
0     120505        0.231968
1     119598        0.283881
2     149324        0.279170
3     148569        0.217365
4     148567        0.189664